name = "feature-voting"
main = "src/entry.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "feature-voting-dev"
database_id = "<ID>"
